#clone the github repo
- name: clone github repo
  hosts: all
  tasks:
    - name: clone repo
      ansibile.builtin.git:
      repo: https://github.com/2105-may24-devops/fletcher-project0
      clone: yes
      dest: ~/