#clone the github repo
- name: clone github repo
  hosts: all
  become: yes
  tasks:

  - name: clone repo
    ansible.builtin.git:
      repo: https://github.com/2105-may24-devops/fletcher-project0
      clone: yes
      dest: /home/fletcher/project0
      version: main