---
# These tasks install and update python3 and git

- name: Install python3, python3-venv, git and pip
  hosts: all
  become: yes
  tasks:
    - name: install python3
      ansible.builtin.package:
        name: python3
        state: latest
    - name: install python3-venv
      ansible.builtin.package:
        name: python3-venv
        state: latest
    - name: install git
      ansible.builtin.package:
        name: git
        state: latest
    - name: install pip
      ansible.builtin.package:
        name: python3-pip
        state: latest