#ansible file for uninstalling project
- name: remove project folder from hosts
  hosts: all
  become: yes
  tasks:
    - name: uninstall project
      file:
        state: absent
        path: /home/fletcher/project0